# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('flags', '0001_initial'),
        ('flags', '0002_auto_20151030_1401'),
        ('flags', '0003_flag_hidden'),
        ('flags', '0004_remove_flag_hidden'),
        ('flags', '0005_flag_enabled_by_default'),
        ('flags', '0006_auto_20151217_2003'),
        ('flags', '0007_unique_flag_site'),
        ('flags', '0008_add_state_conditions'),
        ('flags', '0009_migrate_to_conditional_state'),
        ('flags', '0010_delete_flag_site_fk'),
        ('flags', '0011_migrate_path_data_startswith_to_matches'),
    ]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('condition', models.CharField(default='boolean', max_length=64)),
                ('value', models.CharField(default='True', max_length=127)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='flagstate',
            unique_together=set([('name', 'condition', 'value')]),
        ),
    ]
