# Generated by Django 1.11.15 on 2019-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0012_replace_migrations_for_wagtail_independence'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagstate',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
