# Generated by Django 6.0.2 on 2026-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0013_add_required_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flagstate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="flagstate",
            constraint=models.UniqueConstraint(
                fields=("name", "condition", "value"),
                name="flags_flagstate_unique_name_condition_value",
            ),
        ),
    ]
