# Generated by Django 2.2.12 on 2020-05-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0013_add_required_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('value', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'key')},
            },
        ),
    ]
